CREATE TABLE users (
  name TEXT PRIMARY KEY NOT NULL,
  email TEXT NOT NULL,
  pass_hash TEXT NOT NULL,
  class INTEGER NOT NULL,
  xp INTEGER DEFAULT 0,
  att INTEGER DEFAULT 0,
  def INTEGER DEFAULT 0,
  agi INTEGER DEFAULT 0
);
