CREATE TABLE users (
  name TEXT PRIMARY KEY NOT NULL,
  email TEXT NOT NULL,
  pass_hash TEXT NOT NULL,
  class INTEGER NOT NULL,
  xp INTEGER DEFAULT 0,
  att INTEGER DEFAULT 0,
  def INTEGER DEFAULT 0,
  agi INTEGER DEFAULT 0
);

CREATE TABLE games (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT NOT NULL,
  username TEXT NOT NULL,
  recommendedLevel INTEGER NOT NULL,
  json_data BLOB NOT NULL,
  FOREIGN KEY(username) REFERENCES users(name)
);
